#!/bin/bash
# =============================================================================
# Quarkus K3s Deployment Script
# =============================================================================
# This script builds and deploys the Quarkus application to K3s
# 
# Prerequisites:
#   - Maven 3.9+
#   - Java 21+
#   - kubectl configured for k3s
#   - Container registry access (or use local k3s registry)
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
APP_NAME="quarkus-k3s-poc"
NAMESPACE="${NAMESPACE:-default}"
REGISTRY="${REGISTRY:-docker.io}"
IMAGE_GROUP="${IMAGE_GROUP:-cenzo104}"
VERSION="${VERSION:-1.0.0}"

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Quarkus K3s Deployment Script${NC}"
echo -e "${GREEN}========================================${NC}"

# Function to print step
step() {
    echo -e "\n${YELLOW}▶ $1${NC}"
}

# Function to print success
success() {
    echo -e "${GREEN}✓ $1${NC}"
}

# Function to print error
error() {
    echo -e "${RED}✗ $1${NC}"
    exit 1
}

# Check prerequisites
step "Checking prerequisites..."

if ! command -v mvn &> /dev/null; then
    error "Maven is not installed. Please install Maven 3.9+"
fi

if ! command -v kubectl &> /dev/null; then
    error "kubectl is not installed"
fi

if ! kubectl cluster-info &> /dev/null; then
    error "Cannot connect to Kubernetes cluster. Is k3s running?"
fi

success "All prerequisites met"

# Build the application
step "Building Quarkus application..."
mvn clean package -DskipTests \
    -Dquarkus.container-image.registry=${REGISTRY} \
    -Dquarkus.container-image.group=${IMAGE_GROUP} \
    -Dquarkus.container-image.tag=${VERSION}

success "Application built successfully"

# Check if we should push the image
if [ "${PUSH_IMAGE:-false}" = "true" ]; then
    step "Pushing container image to registry..."
    mvn package -DskipTests \
        -Dquarkus.container-image.push=true \
        -Dquarkus.container-image.registry=${REGISTRY} \
        -Dquarkus.container-image.group=${IMAGE_GROUP} \
        -Dquarkus.container-image.tag=${VERSION}
    success "Image pushed to registry"
fi

# Create namespace if it doesn't exist
step "Ensuring namespace exists..."
kubectl create namespace ${NAMESPACE} --dry-run=client -o yaml | kubectl apply -f -
success "Namespace '${NAMESPACE}' ready"

# Apply ConfigMap and Secrets
step "Applying ConfigMap and Secrets..."
kubectl apply -f k8s/configmap.yaml -n ${NAMESPACE}
success "ConfigMap and Secrets applied"

# Apply Kubernetes manifests generated by Quarkus
step "Deploying to Kubernetes..."
MANIFEST_PATH="target/kubernetes/kubernetes.yml"

if [ -f "$MANIFEST_PATH" ]; then
    kubectl apply -f ${MANIFEST_PATH} -n ${NAMESPACE}
    success "Kubernetes manifests applied"
else
    error "Kubernetes manifest not found at ${MANIFEST_PATH}"
fi

# Apply Ingress (optional)
if [ "${ENABLE_INGRESS:-false}" = "true" ]; then
    step "Applying Ingress..."
    kubectl apply -f k8s/ingress.yaml -n ${NAMESPACE}
    success "Ingress applied"
fi

# Wait for deployment
step "Waiting for deployment to be ready..."
kubectl rollout status deployment/${APP_NAME} -n ${NAMESPACE} --timeout=120s
success "Deployment ready"

# Show deployment status
step "Deployment Status:"
echo ""
kubectl get pods -n ${NAMESPACE} -l app.kubernetes.io/name=${APP_NAME}
echo ""
kubectl get svc -n ${NAMESPACE} -l app.kubernetes.io/name=${APP_NAME}

# Port forward for local testing
echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}  Deployment Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "To test locally, run:"
echo "  kubectl port-forward svc/${APP_NAME} 8080:8080 -n ${NAMESPACE}"
echo ""
echo "Then access:"
echo "  - API:     http://localhost:8080/api/items"
echo "  - Health:  http://localhost:8080/q/health"
echo "  - OpenAPI: http://localhost:8080/q/swagger-ui"
echo "  - Info:    http://localhost:8080/api/info"
echo ""
